### ISSUE TITLE
Add Support for the .netCore 2.2 SDK

### ISSUE THREAD

**Issue by dustinchilson** [cake-build/docker#10]
I have an app that I'd like to do a multi-stage docker build with cake that will be targeting netcoreapp2.2  that doesn't work as this targets the 2.1 sdk. 

The current tag `cakebuild/cake:v0.32.1-2.1-sdk` doesn't work to build a 2.2 app as that sdk isn't new enough. If we could build a set of containers targeting the `microsoft/dotnet:2.2-sdk` as the base it would be awesome.

**Comment by devlead** [comment]
2.1 and 2.2 is out of support but .NET 6 will be added soon.
