### ISSUE TITLE
Build script fail to capture exit code

### ISSUE THREAD

**Issue by tharanga2006** [cake-build/docker#13]
Hi All
I have a following script that is running through bamboo agent

/*****************
echo  "-------------------------Start Compilation  ----------------------"
docker run  --rm -v  $PWD:$mountpoint -w $mountpoint  docker.xxx.x.x.x/syncromatics/build-box:latest cake --dotnetCore="false" --setClean="true" \
                                                                                                                            --package=${arr[0]}  --workDir=${arr[1]} \
                                                                                                                            --releaseName=${arr[2]} 
echo  "-------------------------End Compilation   -------------------------"
echo   " "
rc=$?
echo "ERRRRRRRRRRRRRRRRRRRRRRR"  $rc
if [ $? -ne 0 ]
then
   #
   echo "An error occurred while compile time".
   exit 1 
fi
******************/
inside the build.cake it fails the build with exit code 1.

/************************
An error occurred when executing task 'Build'.
Error: One or more errors occurred.
        MSBuild: Process returned an error (exit code 1).
***********************/

But I cant capture this error using $?. It always return 0.

**Comment by devlead** [comment]
You're getting the result code of the echo statement, you'll need to capture it into an variable right after docker run.

**Comment by tharanga2006** [comment]
Hi devlead,
Right on target thanks.
