### ISSUE TITLE
Merge Docker image into main Cake repo

### ISSUE THREAD

**Issue by pascalberger** [cake-build/docker#19]
We should consider meging Docker repo into main https://github.com/cake-build/cake repository. They both share the same release lifecycle and having them in a single repository would simplify and allow more automation in release process.

**Comment by devlead** [comment]
This is docker repo though

**Comment by pascalberger** [comment]
Thanks updated description

**Comment by devlead** [comment]
I'm doing to close this as builds now
* automatically picks last 10 stable versions of Cake >= 1.0
* would significantly increase Cake build times
* need to execute out of band (security fixes, new base images, etc.)
