### ISSUE TITLE
Switch to use global tool

### ISSUE THREAD

**Issue by devlead** [cake-build/docker#7]

**Comment by gitfool** [comment]
FWIW, [gitfool/cake-docker/Dockerfile](https://github.com/gitfool/cake-docker/blob/master/Dockerfile) worked for me on Azure Pipelines ([Cake.Dungeon/Docker Job](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=52&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=09181c4b-3f3c-50e9-b57f-22616eaa56ea&lineStart=141&lineEnd=142&colStart=1&colEnd=1)). I just had to [workaround](https://github.com/gitfool/Cake.Dungeon/blob/master/azure-pipelines.yml#L20) the missing `TF_BUILD` environment variable in the meantime.
